account/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, reverse_lazy
from account import views

app_name = "account"

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('user_admin/', views.user_admin, name='user_admin'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='account/password_reset.html',
        email_template_name='account/password_reset_email.html',
        subject_template_name='account/password_reset_subject.txt',
        success_url=reverse_lazy('account:password_reset_done')),
        name='password_reset'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset_confirm.html',
        success_url=reverse_lazy('account:password_reset_complete')),
        name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'),
        name='password_reset_done'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_reset_complete.html'),
        name='password_reset_complete'),
]

homecenter/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from homecenter import views

app_name = "homecenter"

urlpatterns = [
#    path('', views.index, name='index'),
    path('light/', views.light, name='light'),
    path('network/', views.network, name='network'),
    path('roller_shutter/', views.roller_shutter, name='roller_shutter'),
    path('nodes_config/', views.nodes_config, name='nodes_config'),
    path('admin/', admin.site.urls),
]

homecenter_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from account.forms import MyLoginView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from homecenter_project import settings

urlpatterns = [
    path('', MyLoginView.as_view(template_name='account/login.html'), name='login'),
    path('account/', include('account.urls', namespace='account')),
    path('homecenter/', include('homecenter.urls', namespace='homecenter')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

homecenter/models.py
from django.db import models


class Controller(models.Model):
    home_id = models.CharField(primary_key=True, unique=True, max_length=60)
    name = models.CharField(verbose_name="Non", blank=True, null=True, max_length=120)
    product = models.CharField(verbose_name="Non", blank=True, null=True, max_length=120)

    def __str__(self):
        """ display name in shell"""
        return self.name

    class META:
        verbose_name = "Contrôleur"


class Node(models.Model):
    controller_node = models.ForeignKey(Controller, on_delete=models.CASCADE, related_name='controller')
    node_id = models.IntegerField(primary_key=True, unique=True)
    name = models.CharField(verbose_name="Nom", blank=True, null=True, max_length=120)
    location = models.CharField(verbose_name="Localisation", blank=True, null=True, max_length=120)
    product_type = models.CharField(verbose_name="Type de produit", max_length=10)
    product_name = models.CharField(verbose_name="Nom du produit", max_length=120)
    manufacturer_name = models.CharField(verbose_name="Fabriquant", max_length=120)
    num_groups = models.IntegerField(verbose_name="N° de groupe", blank=True, null=True)
    is_beaming_device = models.BooleanField(verbose_name="Bon état")
    is_failed = models.BooleanField(verbose_name="Manquant")
    is_ready = models.BooleanField(verbose_name="Prêt")
    is_awake = models.BooleanField(verbose_name="Réveillé")

    def __str__(self):
        """ display name in shell"""
        return "id : {}, nom du produit: {}".format(self.node_id, self.product_name)

    class META:
        verbose_name = "Noeuds"
        constraints = [
            models.UniqueConstraint(fields=['controller_node', ' node_id'], name='unique_controller_node_id')
        ]


class Params(models.Model):
    node_param = models.ForeignKey(Node, on_delete=models.CASCADE)
    index = models.IntegerField()
    label = models.CharField(verbose_name="Nom du paramètre", max_length=120)
    data = models.CharField(verbose_name="Paramètre actuel", max_length=120)

    def __str__(self):
        """ display name in shell"""
        return "{} : {} ".format(self.index, self.label)

    class META:
        verbose_name = "Paramètres"
        constraints = [
            models.UniqueConstraint(fields=['node', 'index'], name='node_value_id')
        ]


class Instances(models.Model):
    node = models.ForeignKey(Node, on_delete=models.CASCADE)
    index = models.IntegerField()
    value_id = models.IntegerField(primary_key=True, unique=True,)
    type = models.CharField(verbose_name="Type d'instance", max_length=120)
    name = models.CharField(verbose_name="Nom", blank=True, null=True, max_length=120)
    location = models.CharField(verbose_name="Pièce", blank=True, null=True, max_length=120)
    level = models.IntegerField(blank=True, null=True)
    state = models.CharField(verbose_name='status', max_length=10)

    def __str__(self):
        """ display name in shell"""
        return "{} : {} ".format(self.index, self.type)

    class META:
        verbose_name = "Instances"
        constraints = [
            models.UniqueConstraint(fields=['node', 'value_id'], name='node_value_id')
        ]

homecenter/forms.py
from django.forms import ModelForm
from .models import Instances


class InstanceForm(ModelForm):
    class Meta:
        model = Instances
        fields = ['name', 'location']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update({'id': 'input_name',
                                                 'class': 'input_name form-control rounded',
                                                 'placeholder': "Porte fenêtre"})

        self.fields['location'].widget.attrs.update({'id': 'input_location',
                                                     'class': 'input_location form-control rounded',
                                                     'placeholder': "Salon"})

homecenter/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect

from .backend.zwave import Zwave
from .backend.rollershutter import Rollershutter
from .backend.light import Light
from .models import Controller, Node, Params, Instances
from .forms import InstanceForm
from .backend.db import update_type_switch

zwave = Zwave()


@login_required(login_url='/')
@user_passes_test(lambda u: u.is_superuser)
def network(request):
    if zwave.network.is_ready:
        switch_state = "On"
        nw_text_state = "démarré !"
    else:
        switch_state = "Off"
        nw_text_state = "arrêté !"

    if request.is_ajax and request.method == 'POST':
        jsmessages = {}
        switch_state = request.POST.get('state')
        if not zwave.network.is_ready and switch_state == "On":
            zwave.start()
            jsmessages['success'] = "Le réseau z-wave est démarré !"
            data = {
                'nw_text_state': "démarré !",
                'messages': jsmessages
            }
            return JsonResponse(data)

        elif zwave.network.is_ready and switch_state == "Off":
            zwave.stop()
            jsmessages['success'] = "Le réseau z-wave est arrêté !"
            data = {
                'nw_text_state': "arrêté !",
                'messages': jsmessages
            }
            return JsonResponse(data)
    else:
        network_state = zwave.network.is_ready
        context = {
            "state": switch_state,
            "network_state": network_state,
            "nw_text_state": nw_text_state
        }
        return render(request, 'homecenter/network.html', context)


@login_required(login_url='/')
def roller_shutter(request):
    roller_shutter_nodes = Instances.objects.filter(index=1). \
        filter(node__product_type__contains="0x030")
    if zwave.network.is_ready:
        nw_state = "On"
    else:
        nw_state = "Off"
    setLevel = 0
    level = 0
    if request.is_ajax and request.method == 'POST':
        jsmessages = {}
        if not zwave.network.is_ready:
            jsmessages['warning'] = "Le réseau z-wave est à l'arrêt !"
            data = {
                'nw_state': nw_state,
                'messages': jsmessages
            }
            return JsonResponse(data)
        else:
            node_id = request.POST.get('node_id')
            setLevel = request.POST.get('setLevel')
            stop = request.POST.get('stop')
            direction = request.POST.get('direction')

            jsmessages.clear()
            rollershutter = Rollershutter(zwave.network, int(node_id))
            if not rollershutter.is_ready:
                jsmessages['warning'] = "Le modules {} n'est pas prêt.". \
                    format(node_id)
                data = {'messages': jsmessages}
                return JsonResponse(data)
            else:
                if int(stop) == 0:
                    jsmessages['success'], level = rollershutter. \
                        set_open_level(int(setLevel))
                else:
                    if int(stop) == 1:
                        if int(direction) == 0:
                            jsmessages['success'], level = rollershutter.stop(
                                True)
                        else:
                            jsmessages['success'], level = rollershutter.stop(
                                False)
                data = {'messages': jsmessages, 'level': level}
                return JsonResponse(data)
    else:
        context = {
            "setLevel": setLevel,
            "level": level,
            "nw_state": nw_state,
            "roller_shutter_nodes": roller_shutter_nodes
        }
        return render(request, 'homecenter/roller_shutter.html', context)


@login_required(login_url='/')
@user_passes_test(lambda u: u.is_superuser)
def nodes_config(request):
    if request.is_ajax and request.method == 'POST':
        jsmessages = {}
        if request.POST.get('calibrate') == 'True':
            if not zwave.network.is_ready:
                jsmessages['warning'] = "Le réseau z-wave est à l'arrêt !"
                data = {
                    'messages': jsmessages
                }
                return JsonResponse(data)
            else:
                node_id = request.POST.get('node_id')
                rollershutter = Rollershutter(zwave.network, int(node_id))
                print("Calibration node: {}".format(node_id))
                rollershutter.calibrate()
                jsmessages['success'] = 'La calibration du volet N°{} ' \
                                        'démarre !'.format(node_id)
                data = {
                    'messages': jsmessages
                }
                return JsonResponse(data)

        elif request.POST.get('type_switch_value'):
            if not zwave.network.is_ready:
                jsmessages['warning'] = "Le réseau z-wave est à l'arrêt !"
                data = {
                    'messages': jsmessages
                }
                return JsonResponse(data)
            else:
                node_id = request.POST.get('node_id')
                type_switch_value = request.POST.get('type_switch_value')
                rollershutter = Rollershutter(zwave.network, int(node_id))
                param_message = rollershutter.set_param(14,
                                                        int(type_switch_value))
                update_type_switch(node_id, type_switch_value)
                jsmessages['success'] = param_message
                data = {
                    'messages': jsmessages
                }
                return JsonResponse(data)

        else:
            instanceForm = InstanceForm(request.POST)
            if instanceForm.is_valid():
                node_id = request.POST.get('node_id')
                node_instance = request.POST.get('node_instance')
                node_name = instanceForm.cleaned_data.get('name')
                node_location = instanceForm.cleaned_data.get('location')
                node = Instances.objects.get(node=node_id, index=node_instance)
                node.name = node_name
                node.location = node_location
                node.save()
                jsmessages['success'] = "Enregistrement réussi"
                data = {
                    "messages": jsmessages
                }
                return JsonResponse(data)
    else:
        roller_shutter_nodes = Instances.objects.filter(index=1). \
            filter(node__product_type__contains="0x030"). \
            select_related('node')
        light_nodes = Instances.objects. \
            filter(node__product_type__contains="0x020"). \
            select_related('node')

        switch_type = Params.objects.filter(index=14). \
            filter(node_param__product_type__contains="0x030"). \
            select_related('node_param')

        instanceForm = InstanceForm()

        context = {
            "instanceForm": instanceForm,
            "roller_shutter_nodes": roller_shutter_nodes,
            "light_nodes": light_nodes,
            "switch_type": switch_type
        }

        return render(request, 'homecenter/config.html', context)


@login_required(login_url='/')
def light(request):
    light_nodes = Instances.objects.filter(node__product_type__contains="0x020")
    if zwave.network.is_ready:
        nw_state = "On"
    else:
        nw_state = "Off"

    if request.is_ajax and request.method == 'POST':
        jsmessages = {}
        if not zwave.network.is_ready:
            jsmessages['warning'] = "Le réseau z-wave est à l'arrêt !"
            data = {
                'nw_state': nw_state,
                'messages': jsmessages
            }
            return JsonResponse(data)
        else:
            node_id = request.POST.get('nodeId')
            node_instance = request.POST.get('nodeInstance')
            setState = request.POST.get('setState')

            light_nodes = Instances.objects.get(node_id=node_id,
                                                value_id=node_instance)
            light = Light(zwave.network, int(node_id), int(light_nodes.index))
            if not light.is_ready:
                jsmessages['success'] = "Le modules n'est pas prêt."
                data = {'messages': messages}
                return JsonResponse(data)
            else:
                if setState == "Off":
                    jsmessages['success'], state = light.set_off()
                else:
                    jsmessages['success'], state = light.set_on()
                light_nodes.state = state
                light_nodes.save()
                jsmessages.clear()

                data = {'messages': jsmessages, 'state': state}
                return JsonResponse(data)
    else:
        context = {
            "nw_state": nw_state,
            "light_nodes": light_nodes
        }
        return render(request, 'homecenter/light.html', context)

homecenter/templates/homecenter/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% load static %}

    <title>HomeCenter - {% block title %}Accueil{% endblock %}</title>

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/c7479c1946.js" crossorigin="anonymous"></script>

    <!-- Google Material Design Icons -->
    <link rel="stylesheet" href="//cdn.materialdesignicons.com/4.9.95/css/materialdesignicons.min.css">
    <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>

    <!-- Theme CSS - Includes Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Theme CSS - HomeCenter -->
    <link href="{% static 'homecenter/css/homecenter.css' %}" rel="stylesheet">

    <!-- Django favicon-->
    <link rel="shortcut icon" type="image/png" href="{% static 'homecenter/img/favico.ico' %}"/>


</head>
<body>
    <header id="header" class="jumbotron jumbotron-fluid">
        <div class="container row col-12">
            <div id="button" class="col-12 col-sm-3 order-3 order-sm-1">
                <button type="button" id="sidebarCollapse" class="btn bg-transparent">
                    <i class="fas fa-align-left"></i>
                    <span>Maison</span>
                </button>
            </div>
            <div id="logo" class="col-2 col-sm-2 text-center text-sm-right order-1 order-sm-2">
                <img src="{% static 'homecenter/img/HomeCenter.png' %}">
            </div>

            <div id="title" class="col-10 col-sm-7 text-center text-sm-left order-2 order-sm-3">
                <h1 class="display-5"><strong>H</strong>ome<strong>C</strong>enter</h1>
                <p class="">Gardez le contrôle de votre domicile!</p>
            </div>

        </div>
    </header>

    <!-- Side nav bar -->
    {% if user.is_authenticated%}
    <div class="wrapper">
        <nav id="sidebar">
            <ul class="list-unstyled components">

                <li class="active">
                    <a href="#home" data-toggle="collapse" aria-expanded="false" class="fa fa-home mdi-24px dropdown-toggle"><i>  Maison</i></a>
                    <br>
                    <ul class="collapse list-unstyled" id="home">
                        <br>
                        <li>
                            <a href="{% url 'homecenter:roller_shutter' %}"><span class="iconify mdi-24px align-left" data-icon="mdi-window-shutter" data-inline="false"></span><i>  Volets</i></a>
                        </li><br>
                        <li>
                            <a href="{% url 'homecenter:light' %}"><span class="iconify mdi-24px" data-icon="raphael:lamp-alt" data-inline="false"></span><i>  Lampes</i></a>
                        </li><br>
                    </ul>
                </li>
                <br>
                {% if user.is_staff == 1 %}
                <li class="active">
                    <a href="#config" data-toggle="collapse"  class="fa fa-gear mdi-24px dropdown-toggle"><i>  Config.</i></a>
                    <ul class="collapse list-unstyled" id="config">
                        <br>
                        <li>
                            <a href="{% url 'homecenter:nodes_config' %}"><span class="iconify mdi-24px" data-icon="bx:bx-network-chart" data-inline="false"></span><i>  Noeuds</i></a>
                        </li><br>
                        <li>
                            <a href="{% url 'homecenter:network' %}"><span class="iconify mdi-24px" data-icon="simple-icons:z-wave" data-inline="false"></span><i>  Réseau</i></a>
                        </li><br>
                        <li>
                            <a href="{% url 'account:user_admin' %}"><span class="iconify mdi-24px" data-icon="mdi:account-cog" data-inline="false"></span><i>  Utilisateurs</i></a>
                        </li>
                    </ul>
                <br>
                </li>
                {% endif %}
                <br>

                <li>
                    <h5><u>{{ user }}</u></h5>
                    <a href="{% url 'account:logout' %}"><span class="iconify mdi-24px" data-icon="mdi-logout" data-inline="false"></span><i>  Déconnection</i></a>
                </li><br>
                <li>
                    <a href="#"><i>A propos</i></a>
                </li>
            </ul>
        </nav>
    </div>
    {% endif %}
        <!-- Page content -->
    <div id="content" class="row col-12">
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
    <!-- Socketio javascript CDN -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.slim.js"></script>
    <!-- Custom scripts for store app -->
    <script src="{% static 'homecenter/js/homecenter.js' %}"></script>
</body>
</html>

homecenter/templates/homecenter/config.html
{% extends 'homecenter/base.html' %}
{% load static %}
{% block content %}
    <div class="col-12">
        <div id="messages" class="col-12 text-center mh-40">
            <input type="hidden" class="" name="nw_state" value="{{ nw_state }}">
            <p class="message offset-2 col-8 rounded alert alert-info d-none"></p>
        </div>
        <div class="row d-flex justify-content-around mx-auto">
        {% for node in roller_shutter_nodes %}
            {% include 'homecenter/config_thumbnail.html' %}
        {% endfor %}
        {% for node in light_nodes %}
            {% include 'homecenter/config_thumbnail.html' %}
        {% endfor %}
        </div>
    </div>
{% endblock %}

homecenter/templates/homecenter/config_thumbnail.html
<div class="rs card rounded text-center col-12 col-sm-10 col-md-8 col-lg-5 col-xl-4 ">
    <div class="card-body text-center col-12">
        <div class="row col-12">
            {% if node.type == 'dimmer' %}
                <div id="icon" class="mdi mdi-window-shutter mdi-48px"></div>
            {% else %}
                <div id="light_icon" class="mdi mdi-lightbulb mdi-48px mdi-yellow"></div>
            {% endif %}
            <div class="col-10 card-title text-center">{{ node.node.product_name }}</div>
        </div>
        <div id='test' class=" card-header">

            <table class="table">
                <tbody class="text-left form-group">
                    <tr class="text-left">
                      <th><label>Id:</label></th>
                      <td id="node_id">{{ node.node_id }}</td>
                    </tr>
                    <tr class="text-left">
                      <th><label>Instance N°:</label></th>
                      <td id="instance_id">{{ node.index }}</td>
                    </tr>
                    <tr class="text-left">
                      <th><label>Instance Id:</label></th>
                      <td id="instance_value_id">{{ node.value_id }}</td>
                    </tr>
                    <tr>
                      <th><label>Fabriquant:</label></th>
                      <td>{{ node.node.manufacturer_name }}</td>
                    </tr>
                        {% csrf_token %}
                        <tr>
                            <th><label for="input_name">Nom:</label></th>
                            <td><input type="text" name="name" maxlength="120" id="input_name"
                                       class="input_name form-control rounded" placeholder="Porte fenêtre"
                                       value="{{ node.name }}">
                            </td>
                        </tr>
                        <tr>
                            <th><label for="input_location">Pièce:</label></th>
                            <td><input type="text" name="location" maxlength="120" id="input_location"
                                       class="input_location form-control rounded" placeholder="Salon"
                                       value="{{ node.location }}">
                            </td>
                        </tr>
                        {% if node.type == 'dimmer' %}
                            <tr class="text-left">
                              <th><label>Interrupteurs:</label></th>
                              <td>
                                <select id="switch_type" name="switch_type" class="switch_type form-control rounded">
                                  <option value="0" {% for type in switch_type %}
                                                        {% if type.node_param_id == node.node_id %}
                                                            {%if type.data == "Momentary switches" %}
                                                                selected
                                                            {% endif %}
                                                        {% endif %}
                                                    {% endfor %} >1. interrupteurs monostables</option>
                                  <option value="1" {% for type in switch_type %}
                                                        {% if type.node_param_id == node.node_id %}
                                                            {% if type.data == "Toggle switches" %}
                                                                selected
                                                            {% endif %}
                                                        {% endif %}
                                                    {% endfor %} >2. interrupteurs bistables</option>
                                  <option value="2" {% for type in switch_type %}
                                                        {% if type.node_param_id == node.node_id %}
                                                            {% if type.data == "Single, momentary switch." %}
                                                                selected
                                                            {% endif %}
                                                        {% endif %}
                                                    {% endfor %} >3. interrupteur unique monostable</option>
                                </select>
                              </td>
                            </tr>
                            <tr>
                              <th><label>Calibration ?</label></th>
                              <td class="text-center"><button id="BtnCalibrate" type="button" class="BtnCalibrate btn btn-primary btn-sm">Calibrer</button></td>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

homecenter/templates/homecenter/light.html
{% extends 'homecenter/base.html' %}
{% load static %}
{% block content %}
    <div class="col-12">
        <div id="messages" class="col-12 text-center mh-40">
            <input type="hidden" class="" name="nw_state" value="{{ nw_state }}">
            <p class="message offset-2 col-8 rounded alert alert-info d-none"></p>
        </div>
        <div class="row">
        {% for node in light_nodes%}
            {% include 'homecenter/light_thumbnail.html' %}
        {% endfor %}
        </div>
    </div>
{% endblock %}

homecenter/templates/homecenter/light_thumbnail.html
{% load static %}
<div id="{{ node.node_id }}" class="card col-1">
    <div class="card-body text-center col-12" >
        <div class="row col-12">
            <div id="light_icon" class="mdi mdi-lightbulb mdi-48px"></div>
            <div class="col-10 card-title text-center">{{ node.name }} <br>{{ node.location }}</div>
        </div>
        <div class="card-header ">
            <input type="hidden" class="light_set_state d-none" value="">
            <h5 id="light_state" class="light_state d-none">{{ node.state }}</h5>
            <div class="inputcontainer">
                {% csrf_token %}
                <input type="hidden" value="{{ node.index }}" class="light_instance" id="{{ node.value_id }}" name="light_instance">
            </div>
            <div class="row col-12">
                <i id="light_switch" class="fas fa-toggle-on fa-rotate-180 mdi-48px light_switch"></i>
            </div>
        </div>
    </div>
</div>

homecenter/templates/homecenter/network.html
{% extends 'homecenter/base.html' %}
{% load static %}
{% block content %}
    <div id="network" class="col-12">
        <div id="messages" class="col-12 text-center mh-40">
            <p class="message offset-2 col-8 rounded alert alert-info d-none"></p>
        </div>
        <div class="text-center mh-40">
            <img id="network_img"
                     src="{% get_static_prefix %}homecenter/img/network/z-wave-vector-logo.svg"
                     alt="network logo">
        </div>
        <div id="network_btn" class="text-center mh-40" >
                <p><i id="nw_text_state">Le réseau est {{ nw_text_state }}</i></p>
                <form id="range-field" method="post">
                    {% csrf_token %}
                    <input type="hidden" value="{{ state }}" class="" id="nw_input" name="state">
                </form>
            <i id="network_switch" class="fas fa-toggle-on fa-rotate-180 mdi-48px switch {{ state }}"></i>
        </div>
    </div>
{% endblock %}

homecenter/templates/homecenter/roller_shutter.html
{% extends 'homecenter/base.html' %}
{% load static %}
{% block content %}
    <div class="col-12">
        <div id="messages" class="col-12 text-center mh-40">
            <input type="hidden" class="" name="nw_state" value="{{ nw_state }}">
            <p class="message offset-2 col-8 rounded alert alert-info d-none"></p>
        </div>
        <div class="row">
        {% for node in roller_shutter_nodes%}
            {% include 'homecenter/rs_thumbnail.html' %}
        {% endfor %}
        </div>
    </div>
{% endblock %}